services:
  devsocial:
    build: .
    container_name: devsocial
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - devsocial-data:/data
      - ./uploads:/app/uploads
    env_file:
      - .env

volumes:
  devsocial-data:
